name: Preparant test cypress a producció
on:
  push:
    branches: ["main"]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v4
      - name: scp a producció
        run: | 
          cd ./nuxt-project
          npm install 
          npm run build
          cd ${{ github.workspace }}
          scp -r -o stricthostchechecking=no -o UserKnownHostsFile=/dev/null -i ./nuxt-project/dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a21rublormar/web/cypress-app-example.daw.inspedralbes.cat/public_html/web/
          
      